[tasks.format_and_fix]
description = "删除未使用的导入并格式化代码"
command = "cargo"
args = ["fix", "--allow-dirty", "--allow-staged"]

[tasks.format]
description = "格式化所有代码文件"
command = "cargo"
args = ["fmt", "--all"]
